# Generated by Django 5.2.5 on 2025-11-15 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tasks', '0005_servicerequest_work_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='سبب الفشل إن وجد', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='moosyl_response',
            field=models.JSONField(blank=True, help_text='الاستجابة الكاملة من Moosyl', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='moosyl_transaction_id',
            field=models.CharField(blank=True, help_text='معرف المعاملة من Moosyl', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bankily', 'Bankily'), ('sedad', 'Sedad'), ('masrivi', 'Masrivi')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['moosyl_transaction_id'], name='payments_pa_moosyl__bd86cb_idx'),
        ),
    ]
