# Generated by Django 5.2.5 on 2025-11-28 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_platformsubscription_usertaskcounter_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'اشتراك', 'verbose_name_plural': 'اشتراكات'},
        ),
        migrations.AlterModelOptions(
            name='usertaskcounter',
            options={'ordering': ['-created_at'], 'verbose_name': 'عداد المهام', 'verbose_name_plural': 'عدادات المهام'},
        ),
        migrations.RemoveField(
            model_name='platformsubscription',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='platformsubscription',
            name='moosyl_transaction_id',
        ),
        migrations.AddField(
            model_name='platformsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertaskcounter',
            name='counted_task_ids',
            field=models.JSONField(blank=True, default=list, help_text='قائمة IDs المهام التي تم حسابها (لمنع الحساب المزدوج)'),
        ),
        migrations.AddField(
            model_name='usertaskcounter',
            name='last_reset_date',
            field=models.DateTimeField(blank=True, help_text='تاريخ آخر إعادة تعيين للعداد', null=True),
        ),
        migrations.AlterField(
            model_name='platformsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ بالمليم (centime). مثال: 800.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformsubscription',
            name='payment_method',
            field=models.CharField(choices=[('benkily', 'Benkily'), ('other', 'Other')], default='benkily', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsubscription',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='معرف المعاملة من Benkily', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformsubscription',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='صالح حتى (30 يوم من تاريخ الدفع)', null=True),
        ),
        migrations.AlterField(
            model_name='usertaskcounter',
            name='accepted_tasks_count',
            field=models.IntegerField(default=0, help_text='عدد المهام المقبولة (للعميل أو العامل)'),
        ),
        migrations.AlterField(
            model_name='usertaskcounter',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='هل المستخدم مشترك (premium)؟'),
        ),
        migrations.AlterField(
            model_name='usertaskcounter',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, help_text='تاريخ آخر دفع للاشتراك', null=True),
        ),
    ]
