# Generated by Django 5.2.5 on 2025-12-12 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_platformsubscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskcounter',
            name='accepted_tasks_count',
        ),
        migrations.RemoveField(
            model_name='usertaskcounter',
            name='counted_task_ids',
        ),
        migrations.RemoveField(
            model_name='usertaskcounter',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='usertaskcounter',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='usertaskcounter',
            name='last_reset_date',
        ),
        migrations.AddField(
            model_name='usertaskcounter',
            name='free_tasks_used',
            field=models.IntegerField(default=0, help_text='عدد المهام المجانية المستخدمة (من أصل 5)'),
        ),
        migrations.AddField(
            model_name='usertaskcounter',
            name='total_subscriptions',
            field=models.IntegerField(default=0, help_text='عدد مرات شراء الحزم (للإحصائيات)'),
        ),
        migrations.CreateModel(
            name='TaskBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_type', models.CharField(default='paid_8_tasks', help_text='نوع الحزمة', max_length=50)),
                ('tasks_included', models.IntegerField(default=8, help_text='عدد المهام في الحزمة')),
                ('tasks_used', models.IntegerField(default=0, help_text='عدد المهام المستخدمة من الحزمة')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=5.0, help_text='المبلغ بالأوقية (MRU)', max_digits=10)),
                ('payment_method', models.CharField(default='moosyl', help_text='طريقة الدفع', max_length=20)),
                ('moosyl_transaction_id', models.CharField(blank=True, help_text='معرف المعاملة من Moosyl', max_length=255, null=True)),
                ('moosyl_payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', help_text='حالة الدفع من Moosyl', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='هل الحزمة نشطة؟')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='تاريخ إنهاء جميع مهام الحزمة', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حزمة مهام',
                'verbose_name_plural': 'حزم المهام',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='payments_ta_user_id_3a351d_idx'), models.Index(fields=['moosyl_transaction_id'], name='payments_ta_moosyl__34798d_idx')],
            },
        ),
    ]
