# Generated by Django 5.2.5 on 2025-12-12 18:12
# Data Migration: تحويل البيانات من النظام القديم إلى الجديد

from django.db import migrations


def migrate_counter_data_forward(apps, schema_editor):
    """
    تحويل البيانات من النظام القديم إلى الجديد
    
    المشكلة: الحقل accepted_tasks_count تم حذفه من Database في 0005
    الحل: نضع قيمة افتراضية منطقية
    
    القاعدة:
    - إذا المستخدم لم يُنشئ حساب جديد → نفترض استخدم 0 مهام مجانية
    - total_subscriptions = 0 (لم يشتركوا بعد)
    """
    UserTaskCounter = apps.get_model('payments', 'UserTaskCounter')
    db_alias = schema_editor.connection.alias
    
    updated_count = 0
    
    print("\n" + "="*60)
    print("🔄 بدء تهيئة بيانات عدادات المهام...")
    print("="*60 + "\n")
    
    # جلب جميع السجلات
    all_counters = UserTaskCounter.objects.using(db_alias).all()
    total_counters = all_counters.count()
    
    if total_counters == 0:
        print("⚠️  لا توجد سجلات لتهيئتها (Database فارغة)")
        print("\n" + "="*60)
        return
    
    print(f"📊 عدد السجلات المراد تهيئتها: {total_counters}\n")
    
    # معالجة كل سجل
    for counter in all_counters:
        try:
            # الحقول القديمة تم حذفها، نبدأ من الصفر
            # المستخدمون القدامى سيبدأون بحساب جديد (5 مهام مجانية)
            counter.free_tasks_used = 0  # يبدأ من 0 (لديه 5 مهام متاحة)
            counter.total_subscriptions = 0
            counter.save(using=db_alias)
            
            updated_count += 1
            
            # عرض التقدم
            if updated_count % 10 == 0 or updated_count == total_counters:
                print(f"✅ تم تهيئة {updated_count}/{total_counters} سجل...")
            
            # تفاصيل للسجلات القليلة الأولى
            if updated_count <= 5:
                user_phone = counter.user.phone if hasattr(counter.user, 'phone') else f"User #{counter.user.id}"
                print(f"   └─ {user_phone}: تم التهيئة → 0/5 مهام مجانية متاحة")
            
        except Exception as e:
            print(f"❌ خطأ في تهيئة السجل {counter.id}: {str(e)}")
            continue
    
    # ملخص النتائج
    print("\n" + "="*60)
    print("✅ اكتملت التهيئة!")
    print(f"   - تم التهيئة بنجاح: {updated_count} سجل")
    print(f"   - جميع المستخدمين لديهم الآن: 5 مهام مجانية")
    print("="*60 + "\n")


def migrate_counter_data_backward(apps, schema_editor):
    """
    عكس العملية (للأمان فقط - لن نستخدمها غالباً)
    """
    print("\n⚠️  عكس التحويل: لا توجد تغييرات فعلية\n")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_usertaskcounter_accepted_tasks_count_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_counter_data_forward,
            migrate_counter_data_backward
        ),
    ]