# Generated by Django 5.2.5 on 2025-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(default='admin@khidma.com', help_text='البريد الإلكتروني للأدمن', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
