# Generated by Django 5.2.5 on 2025-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email_adminprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='الموقع الحالي للعامل - خط العرض', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='الموقع الحالي للعامل - خط الطول', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='دقة الموقع بالأمتار', null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_last_updated',
            field=models.DateTimeField(blank=True, help_text='آخر مرة تم فيها تحديث الموقع الحالي', null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_sharing_enabled',
            field=models.BooleanField(default=False, help_text='تفعيل مشاركة الموقع الحالي - يتحكم فيه العامل'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_sharing_updated_at',
            field=models.DateTimeField(blank=True, help_text='آخر مرة تم تغيير حالة مشاركة الموقع', null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_status',
            field=models.CharField(choices=[('active', 'نشط'), ('stale', 'قديم'), ('disabled', 'معطل')], default='disabled', help_text='حالة مشاركة الموقع', max_length=20),
        ),
    ]
