# Generated by Django 5.2.5 on 2025-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_workerprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='البريد الإلكتروني - للأدمن إجباري، للآخرين اختياري', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='اسم العرض في لوحة التحكم', max_length=100),
        ),
    ]
