# Generated by Django 5.2.5 on 2025-10-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_adminprofile_email_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='preferred_language',
        ),
    ]
