# Generated by Django 5.2.5 on 2025-10-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_clientprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
