# Generated by Django 5.2.5 on 2025-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_clientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='هل الحساب معلق مؤقتاً', verbose_name='معلق مؤقتاً'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء التعليق - إذا كان فارغاً = إيقاف نهائي', null=True, verbose_name='معلق حتى'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='سبب تعليق الحساب', verbose_name='سبب التعليق'),
        ),
    ]
