# Generated by Django 5.2.5 on 2025-11-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_suspended_user_suspended_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_online',
            field=models.BooleanField(default=False, help_text='هل الأدمن متصل حالياً'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='آخر نشاط للأدمن'),
        ),
    ]
