# Generated by Django 5.2.5 on 2025-11-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_adminprofile_is_online_adminprofile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_online',
            field=models.BooleanField(default=False, help_text='هل العميل متصل حالياً'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='آخر ظهور للعميل'),
        ),
    ]
