# Generated by Django 5.2.5 on 2025-11-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_clientprofile_is_online_clientprofile_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='اسم مخصص مثل: المنزل، المكتب، محل أمي', max_length=100, null=True)),
                ('address', models.CharField(help_text='العنوان الكامل مثل: Tevragh Zeina, Nouakchott', max_length=300)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='خط العرض', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='خط الطول', max_digits=11)),
                ('emoji', models.CharField(blank=True, default='📍', help_text='إيموجي اختياري للموقع', max_length=10)),
                ('usage_count', models.PositiveIntegerField(default=1, help_text='عدد مرات استخدام هذا الموقع')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='آخر مرة استخدم فيها هذا الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='المستخدم صاحب الموقع', on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Location',
                'verbose_name_plural': 'Saved Locations',
                'ordering': ['-usage_count', '-last_used_at'],
                'indexes': [models.Index(fields=['user', '-usage_count'], name='users_saved_user_id_836a69_idx'), models.Index(fields=['user', '-last_used_at'], name='users_saved_user_id_686f63_idx')],
                'unique_together': {('user', 'latitude', 'longitude')},
            },
        ),
    ]
