# Generated by Django 5.2.5 on 2025-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_fix_empty_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='البريد الإلكتروني - للأدمن إجباري، للآخرين اختياري', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='رقم الهاتف للعميل/العامل', max_length=20, unique=True),
        ),
    ]
