# Generated by Django 5.2.5 on 2025-12-04 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text="الأيام المتاحة: ['monday', 'tuesday', ...]"),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر المعتاد من Onboarding', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='وصف الخدمة من صفحة Onboarding'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='ساعة نهاية العمل', null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='ساعة بداية العمل', null=True),
        ),
    ]
