# Generated by Django 5.2.5 on 2025-12-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_workerprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('ar', 'العربية'), ('fr', 'Français'), ('en', 'English')], default='fr', help_text='اللغة المفضلة للمستخدم', max_length=2),
        ),
    ]
