# Generated by Django 5.2.5 on 2025-09-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='هل المحادثة نشطة')),
                ('total_messages', models.PositiveIntegerField(default=0, help_text='إجمالي عدد الرسائل')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='وقت آخر رسالة', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='العميل في المحادثة', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_conversations', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(help_text='العامل في المحادثة', limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='نص الرسالة', max_length=1000)),
                ('is_read', models.BooleanField(default=False, help_text='هل تم قراءة الرسالة')),
                ('read_at', models.DateTimeField(blank=True, help_text='وقت قراءة الرسالة', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='المحادثة التي تنتمي إليها الرسالة', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(help_text='مرسل الرسالة', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_content', 'Contenu inapproprié'), ('harassment', 'Harcèlement'), ('scam_fraud', 'Arnaque/Fraude'), ('spam', 'Spam'), ('fake_profile', 'Profil faux'), ('other', 'Autre')], help_text='سبب التبليغ', max_length=30)),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي للمشكلة', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', help_text='حالة التبليغ', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='ملاحظات الإدارة')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='وقت حل التبليغ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, help_text='المحادثة المرتبطة بالتبليغ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.conversation')),
                ('reported_user', models.ForeignKey(help_text='الشخص المُبلَّغ عنه', on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='الشخص الذي قدم التبليغ', on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='الإداري الذي عالج التبليغ', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text='سبب الحظر', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(help_text='المستخدم المحظور', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(help_text='المستخدم الذي قام بالحظر', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker'], name='chat_blocke_blocker_b3c3f8_idx'), models.Index(fields=['blocked'], name='chat_blocke_blocked_24bf56_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'is_active'], name='chat_conver_client__3f8067_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['worker', 'is_active'], name='chat_conver_worker__d61ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='chat_conver_last_me_f07e7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('client', 'worker')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='chat_report_reporte_2e1ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user'], name='chat_report_reporte_bd14dd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='chat_report_status_4844a4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='chat_report_created_d9d75f_idx'),
        ),
    ]
