# Generated by Django 5.2.5 on 2025-10-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deleted_by_worker',
            field=models.BooleanField(default=False),
        ),
    ]
