# Generated by Django 5.2.5 on 2025-10-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_deleted_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_at_by_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deleted_at_by_worker',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
