# Generated by Django 5.2.5 on 2025-09-08 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=10)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('workers_only', 'Workers Only'), ('private', 'Private')], default='workers_only', max_length=20)),
                ('allow_contact_from_workers', models.BooleanField(default=True)),
                ('auto_detect_location', models.BooleanField(default=True)),
                ('search_radius_km', models.PositiveIntegerField(default=10, help_text='Search radius in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Settings',
                'verbose_name_plural': 'Client Settings',
            },
        ),
        migrations.CreateModel(
            name='FavoriteWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Private notes about this worker', max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('times_hired', models.PositiveIntegerField(default=0)),
                ('total_spent_with_worker', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_workers', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Worker',
                'verbose_name_plural': 'Favorite Workers',
                'ordering': ['-added_at'],
                'unique_together': {('client', 'worker')},
            },
        ),
    ]
