# Generated by Django 5.2.5 on 2025-09-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientNotification',
        ),
    ]
