# Generated by Django 5.2.5 on 2025-09-05 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskapplication',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='taskapplication',
            name='proposed_price',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='communication_rating',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='punctuality_rating',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='quality_rating',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Budget proposé en MRU', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='taskapplication',
            name='application_message',
            field=models.TextField(blank=True, default="Je suis disponible pour cette tâche et j'ai l'expérience nécessaire.", help_text='Message du candidat (optionnel)'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='review_text',
            field=models.TextField(blank=True, help_text='Commentaire sur le service (optionnel)'),
        ),
    ]
