# Generated by Django 5.2.5 on 2025-10-04 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='budget',
            field=models.IntegerField(help_text='Budget proposé en MRU', validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
