# Generated by Django 5.2.5 on 2025-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_servicerequest_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='time_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
