# Generated by Django 5.2.5 on 2025-10-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_servicerequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
