# Generated by Django 5.2.5 on 2025-11-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('tasks', '0005_servicerequest_work_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='work_completed_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='work_started_at',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('published', 'Publiée'), ('active', 'En cours'), ('cancelled', 'Annulée')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='notification_type',
            field=models.CharField(choices=[('task_posted', 'Nouvelle tâche publiée'), ('application_received', 'Nouvelle candidature reçue'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature refusée'), ('task_cancelled', 'Tâche annulée'), ('review_received', 'Évaluation reçue')], max_length=50),
        ),
    ]
