# Generated by Django 5.2.5 on 2025-12-11 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'نصية'), ('audio', 'صوتية'), ('both', 'نص + صوت')], default='text', max_length=10, verbose_name='نوع الشكوى')),
                ('category', models.CharField(choices=[('technical', 'مشكلة تقنية'), ('payment', 'مشكلة في الدفع'), ('suggestion', 'اقتراح تحسين'), ('account', 'مشكلة في الحساب'), ('worker_behavior', 'سلوك عامل'), ('client_behavior', 'سلوك عميل'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='فئة المشكلة')),
                ('description', models.TextField(blank=True, help_text='وصف المشكلة (اختياري إذا كان هناك تسجيل صوتي)', null=True, verbose_name='الوصف النصي')),
                ('audio_file', models.FileField(blank=True, help_text='ملف صوتي (MP3, AAC) - max 10MB', null=True, upload_to='complaints/audio/%Y/%m/', verbose_name='التسجيل الصوتي')),
                ('audio_duration', models.PositiveIntegerField(blank=True, help_text='مدة التسجيل بالثواني', null=True, verbose_name='مدة التسجيل')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('resolved', 'محلول'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('important', 'مهم'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('admin_notes', models.TextField(blank=True, help_text='ملاحظات خاصة للأدمن', verbose_name='ملاحظات الأدمن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة')),
                ('user', models.ForeignKey(help_text='المستخدم الذي قدم الشكوى', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='complaints__user_id_366974_idx'), models.Index(fields=['status', '-created_at'], name='complaints__status_f077e8_idx'), models.Index(fields=['category', '-created_at'], name='complaints__categor_b85e62_idx')],
            },
        ),
    ]
