# Generated by Django 5.2.5 on 2025-09-08 13:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='worker_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured images show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(blank=True, help_text='Which service this image relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_gallery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Gallery Image',
                'verbose_name_plural': 'Worker Gallery Images',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=10)),
                ('auto_accept_jobs', models.BooleanField(default=False, help_text='Automatically accept job requests')),
                ('max_daily_jobs', models.PositiveIntegerField(default=5, help_text='Maximum jobs per day')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('clients_only', 'Clients Only'), ('private', 'Private')], default='public', max_length=20)),
                ('travel_radius_km', models.PositiveIntegerField(default=15, help_text='Maximum travel distance in kilometers')),
                ('instant_booking', models.BooleanField(default=True, help_text='Allow clients to book instantly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Settings',
                'verbose_name_plural': 'Worker Settings',
            },
        ),
        migrations.CreateModel(
            name='WorkerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prix de base en MRU', max_digits=10, validators=[django.core.validators.MinValueValidator(100.0)])),
                ('price_type', models.CharField(choices=[('fixed', 'Prix fixe'), ('hourly', 'Par heure'), ('negotiable', 'Négociable')], default='negotiable', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Specific description for this service')),
                ('is_active', models.BooleanField(default=True)),
                ('min_duration_hours', models.PositiveIntegerField(default=1, help_text='Minimum duration in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Service',
                'verbose_name_plural': 'Worker Services',
                'ordering': ['-created_at'],
                'unique_together': {('worker', 'category')},
            },
        ),
    ]
