# Generated by Django 5.2.5 on 2025-09-04 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_created_at_profile_onboarding_completed_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Service description from onboarding')),
                ('service_area', models.CharField(help_text="Zone d'intervention", max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='worker_avatars/')),
                ('available_days', models.JSONField(default=list, help_text="List of available weekdays: ['monday', 'tuesday', ...]")),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Worker Profile',
                'verbose_name_plural': 'Worker Profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='worker_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured images show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(blank=True, help_text='Which service this image relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Gallery Image',
                'verbose_name_plural': 'Worker Gallery Images',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for current', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Experience',
                'verbose_name_plural': 'Worker Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prix de base en MRU', max_digits=10, validators=[django.core.validators.MinValueValidator(100.0)])),
                ('price_type', models.CharField(choices=[('fixed', 'Prix fixe'), ('hourly', 'Par heure'), ('negotiable', 'Négociable')], default='negotiable', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Specific description for this service')),
                ('is_active', models.BooleanField(default=True)),
                ('min_duration_hours', models.PositiveIntegerField(default=1, help_text='Minimum duration in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Service',
                'verbose_name_plural': 'Worker Services',
                'unique_together': {('worker', 'category')},
            },
        ),
    ]
