# Generated by Django 5.2.5 on 2025-09-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_created_at_profile_onboarding_completed_and_more'),
        ('tasks', '0002_remove_taskapplication_available_time_and_more'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text='نوع الإشعار', max_length=30, unique=True)),
                ('title_fr', models.CharField(help_text='العنوان بالفرنسية', max_length=200)),
                ('message_fr', models.TextField(help_text='الرسالة بالفرنسية')),
                ('title_ar', models.CharField(blank=True, help_text='العنوان بالعربية', max_length=200)),
                ('message_ar', models.TextField(blank=True, help_text='الرسالة بالعربية')),
                ('title_en', models.CharField(blank=True, help_text='العنوان بالإنجليزية', max_length=200)),
                ('message_en', models.TextField(blank=True, help_text='الرسالة بالإنجليزية')),
                ('template_variables', models.JSONField(default=list, help_text='قائمة بالمتغيرات المطلوبة في القالب')),
                ('is_active', models.BooleanField(default=True, help_text='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de notification',
                'verbose_name_plural': 'Modèles de notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='تفعيل الإشعارات بشكل عام')),
                ('task_notifications', models.BooleanField(default=True, help_text='إشعارات المهام')),
                ('message_notifications', models.BooleanField(default=True, help_text='إشعارات الرسائل')),
                ('payment_notifications', models.BooleanField(default=True, help_text='إشعارات المدفوعات')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='بداية ساعات الهدوء', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='نهاية ساعات الهدوء', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='المستخدم', on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Paramètres de notification',
                'verbose_name_plural': 'Paramètres de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_published', 'Tâche publiée'), ('worker_applied', 'Prestataire candidat'), ('task_completed', 'Tâche terminée'), ('payment_received', 'Paiement reçu'), ('message_received', 'Message reçu'), ('service_reminder', 'Rappel de service'), ('service_cancelled', 'Service annulé'), ('new_task_available', 'Nouvelle tâche disponible'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature rejetée'), ('task_completed', 'Tâche confirmée terminée'), ('payment_sent', 'Paiement envoyé'), ('message_received', 'Message reçu')], help_text='نوع الإشعار', max_length=30)),
                ('title_key', models.CharField(help_text='مفتاح ترجمة العنوان', max_length=100)),
                ('message_key', models.CharField(help_text='مفتاح ترجمة الرسالة', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='البيانات المستخدمة في الترجمة')),
                ('is_read', models.BooleanField(default=False, help_text='هل تم قراءة الإشعار')),
                ('read_at', models.DateTimeField(blank=True, help_text='وقت القراءة', null=True)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', help_text='أولوية الإشعار', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الإشعار', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='المستلم للإشعار', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profile')),
                ('related_application', models.ForeignKey(blank=True, help_text='طلب العمل المرتبط بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskapplication')),
                ('related_task', models.ForeignKey(blank=True, help_text='المهمة المرتبطة بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.servicerequest')),
                ('related_worker', models.ForeignKey(blank=True, help_text='العامل المرتبط بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
