# Generated by Django 5.2.5 on 2025-09-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='تفعيل الإشعارات بشكل عام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='المستخدم', on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres de notification',
                'verbose_name_plural': 'Paramètres de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_published', 'Tâche publiée'), ('worker_applied', 'Prestataire candidat'), ('task_completed', 'Tâche terminée'), ('payment_received', 'Paiement reçu'), ('message_received', 'Message reçu'), ('service_reminder', 'Rappel de service'), ('service_cancelled', 'Service annulé'), ('new_task_available', 'Nouvelle tâche disponible'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature rejetée'), ('payment_sent', 'Paiement envoyé'), ('message_received', 'Message reçu')], help_text='نوع الإشعار', max_length=30)),
                ('title', models.CharField(help_text='عنوان الإشعار', max_length=200)),
                ('message', models.TextField(help_text='محتوى الإشعار')),
                ('is_read', models.BooleanField(default=False, help_text='هل تم قراءة الإشعار')),
                ('read_at', models.DateTimeField(blank=True, help_text='وقت القراءة', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='المستلم للإشعار', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, help_text='طلب العمل المرتبط بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskapplication')),
                ('related_task', models.ForeignKey(blank=True, help_text='المهمة المرتبطة بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.servicerequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
