# Generated by Django 5.2.5 on 2025-09-18 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Firebase FCM Token', unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', help_text='نوع الجهاز', max_length=10)),
                ('device_name', models.CharField(blank=True, help_text='اسم الجهاز (اختياري)', max_length=100)),
                ('app_version', models.CharField(blank=True, help_text='إصدار التطبيق', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='الجهاز نشط ويستقبل إشعارات')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='آخر استخدام للجهاز')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='تفعيل الإشعارات على هذا الجهاز')),
                ('total_notifications_sent', models.PositiveIntegerField(default=0, help_text='عدد الإشعارات المرسلة لهذا الجهاز')),
                ('last_notification_sent', models.DateTimeField(blank=True, help_text='آخر إشعار تم إرساله', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='مالك الجهاز', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('sent', 'مرسل'), ('delivered', 'تم التسليم'), ('failed', 'فشل'), ('invalid_token', 'رمز غير صالح')], default='pending', help_text='حالة الإرسال', max_length=20)),
                ('firebase_message_id', models.CharField(blank=True, help_text='معرف الرسالة في Firebase', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, help_text='وقت الإرسال', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='وقت التسليم', null=True)),
                ('error_message', models.TextField(blank=True, help_text='رسالة الخطأ إن وجدت')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='عدد محاولات الإعادة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_token', models.ForeignKey(help_text='الجهاز المستهدف', on_delete=django.db.models.deletion.CASCADE, to='notifications.devicetoken')),
                ('notification', models.ForeignKey(help_text='الإشعار الأصلي', on_delete=django.db.models.deletion.CASCADE, related_name='firebase_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['platform'], name='notificatio_platfor_0d3ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['last_used'], name='notificatio_last_us_741dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='notificatio_status_a242db_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_d19621_idx'),
        ),
    ]
