# Generated by Django 5.2.5 on 2025-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken_notificationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_published', 'Tâche publiée'), ('worker_applied', 'Prestataire candidat'), ('task_completed', 'Tâche terminée'), ('payment_received', 'Paiement reçu'), ('message_received', 'Message reçu'), ('service_reminder', 'Rappel de service'), ('service_cancelled', 'Service annulé'), ('new_task_available', 'Nouvelle tâche disponible'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature rejetée'), ('payment_sent', 'Paiement envoyé'), ('message_received', 'Message reçu'), ('new_report', 'Nouveau signalement'), ('low_rating', 'Évaluation négative'), ('large_payment', 'Transaction importante'), ('new_user', 'Nouvel utilisateur'), ('task_completed', 'Tâche terminée'), ('payment_pending', 'Paiement en attente')], help_text='نوع الإشعار', max_length=30),
        ),
    ]
